events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name botdiscord.ru www.botdiscord.ru;

        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name botdiscord.ru www.botdiscord.ru;
        http2 on;

        ssl_certificate /etc/letsencrypt/live/botdiscord.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/botdiscord.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
